export const WISHLIST_GET_REQUEST = 'WISHLIST_GET_REQUEST';
export const WISHLIST_GET_SUCCESS = 'WISHLIST_GET_SUCCESS';
export const WISHLIST_GET_FAIL = 'WISHLIST_GET_FAIL';

export const WISHLIST_ADD_REQUEST = 'WISHLIST_ADD_REQUEST';
export const WISHLIST_ADD_SUCCESS = 'WISHLIST_ADD_SUCCESS';
export const WISHLIST_ADD_FAIL = 'WISHLIST_ADD_FAIL';

export const WISHLIST_REMOVE_REQUEST = 'WISHLIST_REMOVE_REQUEST';
export const WISHLIST_REMOVE_SUCCESS = 'WISHLIST_REMOVE_SUCCESS';
export const WISHLIST_REMOVE_FAIL = 'WISHLIST_REMOVE_FAIL'; 